[project]
name = "fastids-alerts"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.2",
    "uvicorn>=0.31.1",
    "jinja2>=3.1.4",
    "pytailwindcss>=0.2.0",
    "sqlmodel>=0.0.22",
    "alembic>=1.13.3",
]
